### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dennisangemi** [gruppo-angemi/website#34]
- [ ] logo, color palette
- [x] create google my business profile
- [x] https://github.com/ANGEMI-infrastrutture/website/issues/30
- [ ] https://github.com/ANGEMI-infrastrutture/website/issues/11
- [ ] update website with map, phone, description https://github.com/ANGEMI-infrastrutture/website/issues/6
